"""Registered decision rules: score each study's gates and render the report gate tables.

A ``CONFIRMED EDGE`` verdict requires every gate registered in the study's pre-registration:
research/PREREGISTRATION.md ("Decision rule", gates 1-7) for the base study and
research/PREREGISTRATION_variantA.md ("Decision rule", gates 1-7) for Variant A. The two gate
lists live in ``STUDIES``; every numeric threshold is read from ``config.py`` at call time.

Inputs are the statistics as published in the phase reports (``output/phase4_optimize.md``,
``phase5_validation.md``, ``phase6_costs.md`` and their ``variantA_*`` counterparts), parsed at
their printed precision. ``update_report`` renders the table into ``output/REPORT.md`` /
``output/REPORT_variantA.md`` between the ``gate-table`` marker comments; run_06_costs.py and
run_A6_costs.py call it after regenerating the phase reports, and ``python -m src.gates``
re-renders both tables from the committed phase reports without the data cache.
"""
from __future__ import annotations

import math
import re
from dataclasses import dataclass
from pathlib import Path

import config

MARKER_START = "<!-- gate-table:start (generated by src/gates.py from the phase reports; do not edit) -->"
MARKER_END = "<!-- gate-table:end -->"

BENCHMARK_LABELS = {
    "bh_price": "B&H perp price ex-funding",
    "bh_perp_net": "B&H perp net of funding",
}

# Registered gate lists, in pre-registration order. "benchmark" names the buy-and-hold series each
# pre-registration adopted: the base study registered "buy-and-hold BTCUSDT perp (net of funding)";
# Variant A registered "buy-and-hold spot", which the engine computes as the perp's open-to-open
# price return without funding (src/backtest.py, ``bh_spot``).
STUDIES: dict[str, dict] = {
    "base": {
        "prereg": "research/PREREGISTRATION.md",
        "report": "REPORT.md",
        "phase4": "phase4_optimize.md",
        "phase5": "phase5_validation.md",
        "phase6": "phase6_costs.md",
        "benchmark": "bh_perp_net",
        "benchmark_rule": "buy-and-hold perp net of funding",
        "gates": ("oos_sharpe", "benchmark", "plateau", "dsr_fdr", "bootstrap_permutation",
                  "oos_positive", "cost"),
    },
    "variantA": {
        "prereg": "research/PREREGISTRATION_variantA.md",
        "report": "REPORT_variantA.md",
        "phase4": "variantA_phase4.md",
        "phase5": "variantA_phase5.md",
        "phase6": "variantA_phase6.md",
        "benchmark": "bh_price",
        "benchmark_rule": "buy-and-hold spot (computed as B&H perp price ex-funding)",
        "gates": ("oos_sharpe", "benchmark", "plateau", "dsr_fdr", "bootstrap", "permutation",
                  "cost"),
    },
}


@dataclass(frozen=True)
class GateStats:
    """The statistics the registered gates are scored on (one study)."""
    oos_sharpe: float           # aggregated walk-forward OOS net Sharpe (annualised)
    oos_ann_return: float       # aggregated walk-forward OOS annualised return (fraction)
    bh_price: float             # B&H perp open-to-open price return, no funding, same OOS span
    bh_perp_net: float          # B&H perp net of funding, same OOS span
    plateau_ratio: float        # full-sample grid: 3x3 neighbourhood mean / peak Sharpe
    plateau_same_sign: float    # share of neighbourhood cells with the peak's sign
    dsr: float                  # DSR of the full-sample-best config, deflated for n_configs trials
    n_configs: int
    fdr_survivors: int
    boot_lo: float              # stationary block-bootstrap CI of the OOS Sharpe
    boot_hi: float
    perm_p: float               # block-permutation null p-value (gross returns)
    breakeven_bps: float        # one-way; math.inf when the sweep has no zero crossing ("> N bps")
    sweep_max_bps: float        # the N of "> N bps" (the sweep's largest cost); NaN otherwise


@dataclass(frozen=True)
class GateResult:
    number: int
    rule: str
    result: str
    passed: bool


def modelled_cost_bps() -> float:
    """Modelled one-way trading cost (taker fee + slippage), in bps."""
    return config.TAKER_FEE_ONE_WAY * 1e4 + config.SLIPPAGE_BPS_ONE_WAY


def _gate(key: str, study: str, s: GateStats) -> tuple[str, str, bool]:
    """(registered rule, published result, passed) for one gate; thresholds from config."""
    if key == "oos_sharpe":
        return (f"Net OOS Sharpe ≥ {config.EDGE_MIN_NET_SHARPE}", f"{s.oos_sharpe:.3f}",
                s.oos_sharpe >= config.EDGE_MIN_NET_SHARPE)
    if key == "benchmark":
        reg = STUDIES[study]["benchmark"]
        other = "bh_perp_net" if reg == "bh_price" else "bh_price"
        result = (f"{s.oos_sharpe:.3f} vs {getattr(s, reg):.3f} "
                  f"({BENCHMARK_LABELS[other]}: {getattr(s, other):.3f})")
        return (f"Net OOS Sharpe > {STUDIES[study]['benchmark_rule']}, same OOS span", result,
                s.oos_sharpe > getattr(s, reg))
    if key == "plateau":
        ok = (s.plateau_ratio >= config.PLATEAU_MIN_FRACTION
              and s.plateau_same_sign >= config.PLATEAU_MIN_SAME_SIGN_FRAC)
        rule = (f"Contiguous plateau: 3×3 neighbourhood ≥ {config.PLATEAU_MIN_FRACTION:.0%} of the "
                "peak Sharpe, same sign (full-sample grid)")
        return (rule, f"nbhd/peak {s.plateau_ratio:.2f}, same-sign {s.plateau_same_sign:.2f}",
                ok or not config.EDGE_REQUIRE_PLATEAU)
    if key == "dsr_fdr":
        dsr_min = 1.0 - config.EDGE_MAX_DSR_P
        rule = (f"DSR > {dsr_min:.2f} (N = grid size) and ≥ 1 BH-FDR survivor at "
                f"α = {config.EDGE_FDR_ALPHA} (full-sample)")
        return (rule, f"DSR {s.dsr:.3f}; {s.fdr_survivors}/{s.n_configs} survive",
                s.dsr > dsr_min and s.fdr_survivors >= 1)
    boot_rule = f"Stationary block-bootstrap {config.CI_LEVEL}% CI of the OOS Sharpe excludes 0"
    perm_rule = f"permutation null (gross returns) p < {config.EDGE_MAX_PERMUTATION_P}"
    boot_res, perm_res = f"CI [{s.boot_lo:.3f}, {s.boot_hi:.3f}]", f"p = {s.perm_p:.3f}"
    boot_ok, perm_ok = s.boot_lo > 0, s.perm_p < config.EDGE_MAX_PERMUTATION_P
    if key == "bootstrap_permutation":
        return f"{boot_rule}, and {perm_rule}", f"{boot_res}; {perm_res}", boot_ok and perm_ok
    if key == "bootstrap":
        return boot_rule, boot_res, boot_ok
    if key == "permutation":
        return perm_rule.capitalize(), perm_res, perm_ok
    if key == "oos_positive":
        return ("Aggregated walk-forward OOS equity positive", f"ann. return {s.oos_ann_return:+.1%}",
                s.oos_ann_return > 0 or not config.EDGE_REQUIRE_OOS_POSITIVE)
    if key == "cost":
        cost = modelled_cost_bps()
        shown = (f"> {s.sweep_max_bps:.0f} bps" if math.isinf(s.breakeven_bps)
                 else f"{s.breakeven_bps:.0f} bps")
        return (f"Breakeven cost > modelled cost ({cost:.0f} bps one-way: fee + slippage)",
                f"breakeven {shown} one-way", s.breakeven_bps > cost)
    raise KeyError(key)


def evaluate_gates(study: str, stats: GateStats) -> list[GateResult]:
    """Score ``stats`` against the study's registered gate list, in registered order."""
    out = []
    for number, key in enumerate(STUDIES[study]["gates"], start=1):
        rule, result, passed = _gate(key, study, stats)
        out.append(GateResult(number, rule, result, bool(passed)))
    return out


def render_gate_table(study: str, results: list[GateResult]) -> str:
    """Markdown gate table + one-line count, as embedded in the study's report."""
    spec = STUDIES[study]
    passed = [r.number for r in results if r.passed]
    failed = [r.number for r in results if not r.passed]
    count = (f"**{len(passed)} of {len(results)} registered gates pass** "
             f"({', '.join(map(str, passed)) or 'none'}); "
             f"fail: {', '.join(map(str, failed)) or 'none'}.")
    source = (f"*Generated by `src/gates.py` from the statistics published in `{spec['phase4']}`, "
              f"`{spec['phase5']}` and `{spec['phase6']}` (at their printed precision); gate list from "
              f"`{spec['prereg']}`, thresholds from `config.py`.*")
    rows = [f"| {r.number} | {r.rule} | {r.result} | {'PASS' if r.passed else 'FAIL'} |" for r in results]
    lines = ["| # | Registered gate | Published statistic | Pass? |", "|---|---|---|---|", *rows,
             "", count, "", source]
    return "\n".join(lines)


def benchmark_line(study: str, oos_sharpe: float, bh_price: float, bh_perp_net: float) -> str:
    """Phase-4 benchmark lines (both buy-and-hold series, scored on the registered one)."""
    reg = STUDIES[study]["benchmark"]
    reg_value = bh_price if reg == "bh_price" else bh_perp_net
    return (f"- Benchmark over same OOS span: {BENCHMARK_LABELS['bh_price']} Sharpe **{bh_price:.3f}**, "
            f"{BENCHMARK_LABELS['bh_perp_net']} Sharpe **{bh_perp_net:.3f}**\n"
            f"- Beats the registered benchmark ({BENCHMARK_LABELS[reg]})? "
            f"**{'YES' if oos_sharpe > reg_value else 'NO'}**")


# ----------------------------- parsing the published phase reports ----------------------------- #
_NUM = r"(-?\d+(?:\.\d+)?)"
_PATTERNS = {
    "plateau": re.compile(r"^- Plateau(?: test)?: \*\*(?:PASS|FAIL)\*\*.*?(?:mean/peak = \*\*|nbhd/peak )"
                          + _NUM + r".*?same-sign(?: frac)? " + _NUM, re.MULTILINE),
    "oos": re.compile(r"\*\*Aggregated OOS:\*\* net Sharpe \*\*" + _NUM + r"\*\* · ann(?:_ret)? " + _NUM + "%"),
    "benchmark": re.compile(r"(?:BH spot|B&H perp price ex-funding) Sharpe \**" + _NUM
                            + r"\**, (?:B&H perp net of funding|BH perp(?: net)?)(?: Sharpe)? \**" + _NUM),
    "dsr": re.compile(r"DSR \((?:deflated for )?N=(\d+)(?: trials)?\) = " + _NUM),
    "fdr": re.compile(r"BH-FDR[^*\n]*\*\*(\d+)/(\d+)\*\*"),
    "boot": re.compile(r"block-bootstrap \d+% CI[^*\n]*\*\*\[" + _NUM + ", " + _NUM + r"\]\*\*"),
    "perm": re.compile(r"Permutation null:.*?\*\*p = " + _NUM + r"\*\*"),
    "breakeven": re.compile(r"Breakeven one-way cost[^\n]*?(>\s*)?(\d+(?:\.\d+)?) bps"),
}


def _find(key: str, text: str, source: Path) -> re.Match:
    m = _PATTERNS[key].search(text)
    if m is None:
        raise ValueError(f"{source}: no '{key}' statistic found")
    return m


def parse_published_stats(study: str, output_dir: Path | None = None) -> GateStats:
    """Read the gate statistics from a study's published phase-4/5/6 markdown reports."""
    out = Path(output_dir) if output_dir is not None else config.OUTPUT_DIR
    spec = STUDIES[study]
    p4, p5, p6 = (out / spec[k] for k in ("phase4", "phase5", "phase6"))
    t4, t5, t6 = (p.read_text(encoding="utf-8") for p in (p4, p5, p6))

    plateau = _find("plateau", t4, p4)
    oos = _find("oos", t4, p4)
    bench = _find("benchmark", t4, p4)
    dsr = _find("dsr", t5, p5)
    fdr = _find("fdr", t5, p5)
    boot = _find("boot", t5, p5)
    perm = _find("perm", t5, p5)
    be = _find("breakeven", t6, p6)
    lower_bound = be.group(1) is not None
    be_value = float(be.group(2))
    if int(fdr.group(2)) != int(dsr.group(1)):
        raise ValueError(f"{p5}: BH-FDR family size {fdr.group(2)} != DSR trial count {dsr.group(1)}")
    return GateStats(
        oos_sharpe=float(oos.group(1)), oos_ann_return=float(oos.group(2)) / 100.0,
        bh_price=float(bench.group(1)), bh_perp_net=float(bench.group(2)),
        plateau_ratio=float(plateau.group(1)), plateau_same_sign=float(plateau.group(2)),
        dsr=float(dsr.group(2)), n_configs=int(dsr.group(1)), fdr_survivors=int(fdr.group(1)),
        boot_lo=float(boot.group(1)), boot_hi=float(boot.group(2)), perm_p=float(perm.group(1)),
        breakeven_bps=math.inf if lower_bound else be_value,
        sweep_max_bps=be_value if lower_bound else math.nan,
    )


def gate_table_for(study: str, output_dir: Path | None = None) -> str:
    return render_gate_table(study, evaluate_gates(study, parse_published_stats(study, output_dir)))


def update_report(study: str, output_dir: Path | None = None) -> str:
    """Re-render the study's gate table in place between the marker comments of its report."""
    out = Path(output_dir) if output_dir is not None else config.OUTPUT_DIR
    path = out / STUDIES[study]["report"]
    text = path.read_text(encoding="utf-8")
    start, end = text.find(MARKER_START), text.find(MARKER_END)
    if start == -1 or end < start:
        raise ValueError(f"{path}: gate-table markers not found")
    table = gate_table_for(study, out)
    text = text[:start + len(MARKER_START)] + "\n" + table + "\n" + text[end:]
    path.write_text(text, encoding="utf-8", newline="\n")
    return table


def main() -> None:
    for study in STUDIES:
        table = update_report(study)
        print(f"{study}: {table.splitlines()[-3]}")


if __name__ == "__main__":
    main()
